# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-04 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_mustbuy_nav_shop_wheel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mustbuy',
            old_name='nmae',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='nav',
            old_name='nmae',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='nmae',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='wheel',
            old_name='nmae',
            new_name='name',
        ),
    ]
