# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-04 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_mainshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainshow',
            name='brandname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='childcid1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='childcid2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='childcid3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='img1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='img2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='img3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='longname1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='longname2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='longname3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='marketprice1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='marketprice2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='marketprice3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='price1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='price2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='price3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='productid1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='productid2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='productid3',
            field=models.CharField(max_length=255),
        ),
    ]
