# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-05 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_goodstypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon_name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('is_use', models.BooleanField(default=True)),
            ],
        ),
    ]
