# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-07 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_fun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exceptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField()),
                ('error_msg', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
