# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-07 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20190307_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='good_num',
            new_name='goods_num',
        ),
    ]
